"""add order_lines table from ERP OEEL export

Revision ID: 0efa5e13e481
Revises: 55e2a7aae6d9
Create Date: 2026-08-03 19:45:14.473030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efa5e13e481'
down_revision: Union[str, Sequence[str], None] = '55e2a7aae6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_pointer', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('order_suffix', sa.String(length=5), nullable=False),
    sa.Column('line_number', sa.String(length=10), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=True),
    sa.Column('product_category', sa.String(length=10), nullable=True),
    sa.Column('product_line', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('quantity_ordered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity_shipped', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status_type', sa.String(length=5), nullable=True),
    sa.Column('transaction_type', sa.String(length=10), nullable=True),
    sa.Column('warehouse', sa.String(length=10), nullable=True),
    sa.Column('sales_rep_in', sa.String(length=10), nullable=True),
    sa.Column('sales_territory', sa.String(length=10), nullable=True),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('requested_ship_date', sa.Date(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('cancel_date', sa.Date(), nullable=True),
    sa.Column('source_synced_at', sa.DateTime(), nullable=True),
    sa.Column('erp_created_at', sa.DateTime(), nullable=True),
    sa.Column('erp_modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_number', 'order_suffix'], ['orders.order_number', 'orders.order_suffix'], name='fk_order_lines_order'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number', 'order_suffix', 'line_number', name='uq_order_line'),
    sa.UniqueConstraint('row_pointer')
    )
    op.create_index(op.f('ix_order_lines_id'), 'order_lines', ['id'], unique=False)
    op.create_index(op.f('ix_order_lines_order_number'), 'order_lines', ['order_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_lines_order_number'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_id'), table_name='order_lines')
    op.drop_table('order_lines')
    # ### end Alembic commands ###
