"""rebuild orders table from ERP OEEH export

Revision ID: 55e2a7aae6d9
Revises: f0d8794bbae6
Create Date: 2026-07-30 13:20:15.024248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e2a7aae6d9'
down_revision: Union[str, Sequence[str], None] = 'f0d8794bbae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Replaces the demo `orders` table (order_number/customer_name/status/
    expected_delivery/delivery_address) with one modeled on the real ERP
    OEEH order-entry-header export. Hand-written instead of autogenerated
    add_column/alter_column steps because this is a full schema replacement,
    not an incremental change, and the demo rows being dropped are disposable
    seed data.
    """
    op.drop_table('orders')

    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('row_pointer', sa.String(length=36), nullable=False),

        sa.Column('order_number', sa.String(length=20), nullable=False),
        sa.Column('order_suffix', sa.String(length=5), nullable=False, server_default='0'),

        sa.Column('customer_no', sa.String(length=20), nullable=True),
        sa.Column('customer_po', sa.String(length=100), nullable=True),
        sa.Column('ship_to_no', sa.String(length=10), nullable=True),
        sa.Column('customer_name', sa.String(length=120), nullable=True),
        sa.Column('contact_name', sa.String(length=120), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),

        sa.Column('address_line1', sa.String(length=255), nullable=True),
        sa.Column('address_line2', sa.String(length=255), nullable=True),
        sa.Column('address_line3', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=20), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('country', sa.String(length=5), nullable=True),

        sa.Column('status_code', sa.String(length=10), nullable=True),
        sa.Column('backorder_stage', sa.String(length=5), nullable=True),
        sa.Column('transaction_type', sa.String(length=10), nullable=True),
        sa.Column('order_source', sa.String(length=50), nullable=True),

        sa.Column('entered_date', sa.Date(), nullable=True),
        sa.Column('promised_date', sa.Date(), nullable=True),
        sa.Column('requested_ship_date', sa.Date(), nullable=True),
        sa.Column('ship_date', sa.Date(), nullable=True),
        sa.Column('invoice_date', sa.Date(), nullable=True),
        sa.Column('cancel_date', sa.Date(), nullable=True),

        sa.Column('total_order_amount', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('total_line_amount', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('total_invoice_amount', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('total_qty_ordered', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('total_qty_shipped', sa.Numeric(precision=12, scale=2), nullable=True),

        sa.Column('ship_via', sa.String(length=10), nullable=True),
        sa.Column('warehouse', sa.String(length=10), nullable=True),
        sa.Column('taken_by', sa.String(length=50), nullable=True),
        sa.Column('sales_rep_in', sa.String(length=10), nullable=True),
        sa.Column('terms_type', sa.String(length=10), nullable=True),

        sa.Column('source_synced_at', sa.DateTime(), nullable=True),
        sa.Column('erp_created_at', sa.DateTime(), nullable=True),
        sa.Column('erp_modified_at', sa.DateTime(), nullable=True),

        sa.UniqueConstraint('row_pointer', name='uq_orders_row_pointer'),
        sa.UniqueConstraint('order_number', 'order_suffix', name='uq_order_number_suffix'),
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')

    op.create_table(
        'orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_number', sa.String(length=20), nullable=False),
        sa.Column('customer_name', sa.String(length=120), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False,
                  comment='E.g. Processing | Shipped | Out for Delivery | Delivered | Cancelled'),
        sa.Column('expected_delivery', sa.Date(), nullable=False),
        sa.Column('delivery_address', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_number', name='uq_order_number'),
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
