"""add products table from ERP ICSP export

Revision ID: 6df0bb5752d7
Revises: 0efa5e13e481
Create Date: 2026-08-04 10:36:49.372226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df0bb5752d7'
down_revision: Union[str, Sequence[str], None] = '0efa5e13e481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_pointer', sa.String(length=36), nullable=False),
    sa.Column('company_no', sa.String(length=5), nullable=False),
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('lookup_name', sa.String(length=60), nullable=True),
    sa.Column('description_1', sa.String(length=60), nullable=True),
    sa.Column('description_2', sa.String(length=60), nullable=True),
    sa.Column('description_extended', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('product_type', sa.String(length=5), nullable=True),
    sa.Column('status_code', sa.String(length=5), nullable=True),
    sa.Column('brand_code', sa.String(length=10), nullable=True),
    sa.Column('manufacturer_product', sa.String(length=60), nullable=True),
    sa.Column('model_code', sa.String(length=30), nullable=True),
    sa.Column('stocking_unit', sa.String(length=10), nullable=True),
    sa.Column('selling_unit', sa.String(length=10), nullable=True),
    sa.Column('counting_unit', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('height', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('width', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('length', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('cubes', sa.Numeric(precision=14, scale=5), nullable=True),
    sa.Column('country_of_origin', sa.String(length=5), nullable=True),
    sa.Column('warranty_type', sa.String(length=5), nullable=True),
    sa.Column('warranty_length', sa.Integer(), nullable=True),
    sa.Column('tariff_code', sa.String(length=20), nullable=True),
    sa.Column('unspsc', sa.String(length=20), nullable=True),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('last_change_date', sa.Date(), nullable=True),
    sa.Column('source_synced_at', sa.DateTime(), nullable=True),
    sa.Column('erp_created_at', sa.DateTime(), nullable=True),
    sa.Column('erp_modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_no', 'product_code', name='uq_product_company_code'),
    sa.UniqueConstraint('row_pointer')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
